// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_mulligan = "CgkIoMnq07EKEAIQDw"; // <GPGSID>
        public const string achievement_getting_started = "CgkIoMnq07EKEAIQBw"; // <GPGSID>
        public const string achievement_temple_of_doom = "CgkIoMnq07EKEAIQEA"; // <GPGSID>
        public const string achievement_its_a_trap = "CgkIoMnq07EKEAIQCg"; // <GPGSID>
        public const string achievement_brotherly_love = "CgkIoMnq07EKEAIQAw"; // <GPGSID>
        public const string achievement_gr8_b8_m8 = "CgkIoMnq07EKEAIQDg"; // <GPGSID>
        public const string achievement_all_star = "CgkIoMnq07EKEAIQAQ"; // <GPGSID>
        public const string achievement_all_tuckered_out = "CgkIoMnq07EKEAIQBg"; // <GPGSID>
        public const string achievement_legend_of_the_hidden_temple = "CgkIoMnq07EKEAIQCA"; // <GPGSID>
        public const string achievement_bear_with_me = "CgkIoMnq07EKEAIQBQ"; // <GPGSID>
        public const string achievement_sister_sister = "CgkIoMnq07EKEAIQBA"; // <GPGSID>
        public const string achievement_going_bearzerk = "CgkIoMnq07EKEAIQDQ"; // <GPGSID>
        public const string achievement_lasers_and_feelings = "CgkIoMnq07EKEAIQCw"; // <GPGSID>
        public const string achievement_these_belong_in_a_museum = "CgkIoMnq07EKEAIQAg"; // <GPGSID>
        public const string achievement_hello_darkness = "CgkIoMnq07EKEAIQCQ"; // <GPGSID>
        public const string achievement_family_reunion = "CgkIoMnq07EKEAIQDA"; // <GPGSID>
}

